### ISSUE TITLE
Steam-Rep-Bot problem, can't run it fully.

### ISSUE THREAD

**Issue by ovykun1121** [andrewda/node-steam-guide#106]
Hello!
I tried the +Rep bot by agasking1337 (https://github.com/agasking1337/steam-auto-comment) but when I try to actually start it (node index.js), the only message displayed is "Logged In!", and nothing else after.

Notice that since the NotePad file was outdated I modified it myself by replacing SteamUser.Steam.EPersonaState with SteamUser.EPersonaState.

**Comment by andrewda** [comment]
See my response to https://github.com/DoctorMcKay/node-steam-user/issues/303
