### ISSUE TITLE
SyntaxError: Unexpected token 'else' 

### ISSUE THREAD

**Issue by OHsit** [andrewda/node-steam-guide#116]
SyntaxError: Unexpected token 'else'
←[90m    at Object.compileFunction (node:vm:360:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1055:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1090:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1004:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:839:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m
hepl me fix it!!!!

**Comment by Meganitrospeed** [comment]
You have a syntax error. Some else is wrongly formated. You left our the important part: the code

**Comment by Meganitrospeed** [comment]
As said, don't close issues without commenting what error you had.
