### ISSUE TITLE
Cannot trade another steam items

### ISSUE THREAD

**Issue by Schknheit** [andrewda/node-steam-guide#13]

**Comment by andrewda** [comment]
What game are you trying to trade items for? Could you paste the code you're using?

**Comment by Schknheit** [comment]
Im using the code that was giving on the second part called "sending trade offer", without the request for a item when the bot sends the trade offer. Im trying it with payday. Im using my phone now, so i cant give the code to you

**Comment by andrewda** [comment]
Alright. When you get back to your computer please share the code so I can test it out and try to debug it :)

**Comment by Schknheit** [comment]
Here it is

const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const SteamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');

const client = new SteamUser();
const community = new SteamCommunity();
const manager = new TradeOfferManager({
	steam: client,
	community: community,
	language: 'en'
});

const logOnOptions = {
	accountName: 'user',
	password: 'pass',
	twoFactorCode: SteamTotp.generateAuthCode('my_2fa')
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('Logged into Steam');

	client.setPersona(SteamUser.Steam.EPersonaState.Online);
});

client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies);

	community.setCookies(cookies);
	community.startConfirmationChecker(10000, 'secret_code');

	sendRandomItem();
});

manager.on('newOffer', (offer) => {
	if (offer.partner.getSteamID64() === 'my_steamid_to_recieve_items') {
		offer.accept((err, status) => {
			if (err) {
				console.log(err);
			} else {
				console.log(`Accepted offer. Status: ${status}.`);
			}
		});
	} else {
		offer.decline((err) => {
			if (err) {
				console.log(err);
			} else {
				console.log('Canceled offer from scammer.');
			}
		});
	}
});
function sendRandomItem() {
	manager.loadInventory(218620, 2, true, (err, inventory) => {
		if (err) {
			console.log(err);
		} else {
			const offer = manager.createOffer('my_steamid_to_recieve_items');
			const item = inventory[Math.floor(Math.random() * inventory.length - 1)];

			offer.addMyItem(item);
			offer.setMessage(`Lucky you! You get a ${item.name}!`);
			offer.send((err, status) => {
				if (err) {
					console.log(err);
				} else {
					console.log(`Sent offer. Status: ${status}.`);
				}
			});
		}
	});
}

**Comment by Schknheit** [comment]
By the way, I tested it with csgo and the trade was sent but I didnt recive the notification. Gonna look around for something.
