### ISSUE TITLE
Can i do the bot without the website ?

### ISSUE THREAD

**Issue by xLeeJYx** [andrewda/node-steam-guide#17]
Can i do the bot without the website ? And how where do i set the price of an item ? I dont think ill need a website for my bot for now.

**Comment by FinleyCorrigan** [comment]
You can use this pre-built bot: https://github.com/Arze1/CSGO-Overpay-Bot

**Comment by xLeeJYx** [comment]
Im not looking for csgo bot though, im looKing for bot that banks tf2 items

**Comment by andrewda** [comment]
Hi, sorry for the super late response.

You'll be able to apply the knowledge you learn from this guide to make the small changes necessary in order for the bot to work without a website. At the moment, the guide isn't complete, but I'm slowly adding more and would love contributions from others!

Thanks!
