### ISSUE TITLE
How do you style the HBS files?

### ISSUE THREAD

**Issue by AidanLawrenceG** [andrewda/node-steam-guide#19]
I can't see to figure out how to link the CSS file to the HBS file, even though I use the same linking method as I would in any ordinary HTML file.

**Comment by andrewda** [comment]
Could you show me the code that you tried? Also, if you open up Chrome Dev Tools, are there any errors in your console?

**Comment by AidanLawrenceG** [comment]
[Here](http://i.imgur.com/QypLWAb.png) is the error console.

[Here](http://i.imgur.com/CAaBVo8.png) is how I linked it.

[Here](http://i.imgur.com/3QQtrHS.png) is the file structure.

**Comment by andrewda** [comment]
Not sure if you've gotten to Chapter 6.2 yet, but try adding [this](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%206%20-%20Connecting%20Sites%20and%20Bots/Chapter%206.2%20-%20Getting%20Started/project10/app.js#L95) and putting your `index.css` in the `public` directory. That should work.

**Comment by AidanLawrenceG** [comment]
Ah, adding it to the public directory worked like a charm thanks.
