### ISSUE TITLE
Where can I find 'your_identity_secret' ?

### ISSUE THREAD

**Issue by aboyobam** [andrewda/node-steam-guide#20]
Need help

**Comment by andrewda** [comment]
Hi! Your identity secret is a secret string generated when you first enable 2FA on your account. If you're using an account with 2FA already enabled from a mobile device, you can get the secrets from that file on your phone. There are several tutorials on this for Android and iOS (here's one for iOS I found from Google: http://forums.backpack.tf/index.php?/topic/45995-guide-how-to-get-your-shared-secret-from-ios-device-steam-mobile/). If you're using Steam Desktop Authenticator, your identity secret is also stored in your profile file. Finally, if you don't have 2FA enabled, you can either keep it disabled and remove that part from your code, or you can enable it using [node-steam-user](https://github.com/DoctorMcKay/node-steam-user#enabletwofactorcallback) (strongly suggested).

Hope this help!
