### ISSUE TITLE
Bot ignores my tradeoffers.

### ISSUE THREAD

**Issue by AndrewRAN** [andrewda/node-steam-guide#21]
Here's the code;
`const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const SteamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');

const client = new SteamUser();
const community = new SteamCommunity();
const manager = new TradeOfferManager({
	steam: client,
	community: community,
	language: 'en'
});

const logOnOptions = {
	accountName: 'MY_LOGIN_HERE',
	password: 'MY_PASSWORD_HERE',
	twoFactorCode: SteamTotp.generateAuthCode('MY_AUTHCODE_HERE')
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('Logged into Steam');
	client.setPersona(SteamUser.Steam.EPersonaState.Online);
	client.gamesPlayed("Steam Bot");
});

client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies);

	community.setCookies(cookies);
	community.startConfirmationChecker(10000, 'Lu++M3MNzsf3l0FsE/jKN4X6ZkE=');
});

manager.on('newOffer', (offer) => {
	if (offer.partner.getSteamID64() === '76561198360548976') {
		offer.accept((err, status) => {
			if (err) {
				console.log(err);
			} else {
				console.log(`Accepted offer. Status: ${status}.`);
			}
		});
	}
});`

It loggs in successfully and status is going ONLINE and everything is fine excepting the bot ignores offers and nothing is written in console. Help please.

**Comment by andrewda** [comment]
Are your trades coming from the user with SteamID `76561198360548976`?

**Comment by AndrewRAN** [comment]
Of course.

**Comment by AndrewRAN** [comment]
Do I have to write my cookies and sessionid here?
`client.on('webSession', (sessionid, cookies) => {
manager.setCookies(cookies);

community.setCookies(cookies);
community.startConfirmationChecker(10000, 'Lu++M3MNzsf3l0FsE/jKN4X6ZkE=');
});`

**Comment by AndrewRAN** [comment]
Man, I used another code for returning the error in console and it returned an **Access denied** error:
http://prntscr.com/fit31x

**Comment by AndrewRAN** [comment]
Ugh, I googled a bit, and now I know that I cannot use Steam Bot on not activated accounts ;(

**Comment by AndrewRAN** [comment]
I used the script on my main activated account, it successfully works, but doesn't confirm trades.

**Comment by AndrewRAN** [comment]
OMG, I confused my sharesecret and indentitysecret. Everything works fine right now. Thanks.
