### ISSUE TITLE
Error when i try to log in with steam

### ISSUE THREAD

**Issue by presianaleksandrov** [andrewda/node-steam-guide#24]
Hello, 
I have error when im redirected to steam page. After i click login i recieve message error.
![error](https://user-images.githubusercontent.com/29524871/27264376-9c159d70-5485-11e7-94ad-96b9d4f66974.png)

**Comment by presianaleksandrov** [comment]
I defined proper domain for my api key.

**Comment by andrewda** [comment]
Looks like a Steam issue to me. Can you open up the dev tools and see if there's anything printed in the console?

**Comment by presianaleksandrov** [comment]
Hello, again. There is no problem in console printed.

**Comment by andrewda** [comment]
Weird. And the issue is still occurring? 

Make sure your API key is correct again. If so I'll mess around a bit tonight to see what the issue might be.

**Comment by andrewda** [comment]
Looks like this is probably an issue on Steam's end. Can you check again to see if the issue is resolved? Another thing to check is that your "realm" is correct if you're trying to access the page from somewhere other than `http://localhost:3037`.

**Comment by Alevale** [comment]
It's working perfectly for me, could you add logs for the errors? And maybe how did you configure the origins for the API key?
