### ISSUE TITLE
Command Prompt does not responding

### ISSUE THREAD

**Issue by EliteOneTube** [andrewda/node-steam-guide#25]
When i try to start the bot with node project1.js nothing happens

**Comment by toomi17** [comment]
Share the code here, maybe I could help you. Remember hide acc name and pass.

**Comment by EliteOneTube** [comment]
const SteamUser = require('steam-user');
const config = require('./config.json');
const client = new SteamUser();


const logOnOptions = {
	accountName: config.username,
	password: config.password
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('succesfully logged on.');
	client.setPersona(SteamUser.Steam.EPersonaState.Online);
});

This is the code and it is a bit different

**Comment by toomi17** [comment]
When you run this it should ask for your steam guard code. Continue reading chapter 1.4 and add your shared_secret.

**Comment by EliteOneTube** [comment]
![capture](https://user-images.githubusercontent.com/29592920/27470643-9f51b35e-57fd-11e7-8e1f-9f79eefad2aa.PNG)

**Comment by andrewda** [comment]
I'm unable to duplicate the issue you're facing – the code you posted above works fine for me. All I can suggest is that you verify that your username and password are correct.

**Comment by JamezPabz** [comment]
I'm having the same exact problem. I've tried everything but to no avail
