### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Hello661** [andrewda/node-steam-guide#26]
I put in my shared secrets but when I ran it with node this error occurred help, please?

**Comment by andrewda** [comment]
Please share the full stacktrace of the error.

**Comment by Hello661** [comment]
You want me to share a screenshot of my code or what the full length of the error?

**Comment by andrewda** [comment]
You forgot a comma at the end of line 33. Are you running this code from one of the chapters? There might be a typo somewhere.

**Comment by Hello661** [comment]
Can I give you a screenshot of my code? I will blur out personal information obviously.

**Comment by andrewda** [comment]
Sure

**Comment by Hello661** [comment]
![code](https://user-images.githubusercontent.com/29759387/27653603-95bd3d04-5c0d-11e7-9586-5c3bb8f88736.png)

**Comment by andrewda** [comment]
Are you _absolutely certain_ that this is the code you're running? You blurred out the path at the top of your Sublime window, but is the file you're editing located at `C:\Users\mikea\Desktop\CustomBot\bot.js`? If so, here's what I would do to try and fix the problem:

1. Maybe that "comma" at the end of line 33 is not really a comma. Try deleting it and adding a new comma.
1. If 1 doesn't work, try copy and pasting your code into a new file and running it from there. See if the issue persists in the new file.

**Comment by Hello661** [comment]
![newerrorful](https://user-images.githubusercontent.com/29759387/27655400-34c175e6-5c13-11e7-929b-7a8835bab6f9.png)
I did everything you said but now a new error showed up...

**Comment by andrewda** [comment]
I'm guessing you don't have `const SteamCommunity = require('steamcommunity')` at the top of your file.

**Comment by Hello661** [comment]
Thank you so much for your help! I finally fixed it!

**Comment by andrewda** [comment]
Does the bot print anything in console?

**Comment by Hello661** [comment]
Nope

**Comment by andrewda** [comment]
You should add a `console.log` right before line 20 in order to see when a new trade offer comes in. Something like this:

```javascript
manager.on('newOffer', (offer) => {
    console.log(`Got new offer with partner ${offer.partner.getSteamID64()}`);
    // ... rest of your code ...
});
```

**Comment by Hello661** [comment]
So I put in the code like so, then I restarted the bot sent a trade offer and nothing...![trade](https://user-images.githubusercontent.com/29759387/27663290-9f5dedbe-5c2f-11e7-8576-882a2abb0b0e.png)

**Comment by andrewda** [comment]
Hmm strange... Sounds like you're not being logged in fully. Is your bot account premium?

**Comment by Hello661** [comment]
Premium on tf2?

**Comment by andrewda** [comment]
I used the word premium, but meant if the account has a game/item purchased worth $5 or more. I believe that's still a requirement in order to accept trade offers, but it's been a while since I've setup new Steam bot accounts.

**Comment by Hello661** [comment]
Well I just looked at the steam website and it didn't say anything about trading with a limited account, it just says steam trading cards.
https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663

**Comment by andrewda** [comment]
If you go onto your bot's account, can you manually accept the trade offer? If not, that's probably the issue.

**Comment by Hello661** [comment]
I tried it and yes I could manually accept the offer...

**Comment by andrewda** [comment]
Interesting alright, I'll look into it more tonight if I can.

**Comment by Hello661** [comment]
Alright thanks

**Comment by Hello661** [comment]
Any updates on the issue?

**Comment by andrewda** [comment]
Sorry for the late response. I can't seem to duplicate this issue. The code is working fine on my bot account.

**Comment by Hello661** [comment]
Hmm... Should I send you a screenshot of my code again? Maybe you can compare the code and figure out the problem.

**Comment by andrewda** [comment]
Could you make a GitHub Gist with your entire code (http://gist.github.com), obviously removing your credentials and secrets.

**Comment by Hello661** [comment]
https://gist.github.com/Hello661/ea2da04808a403fdb989797fa5476ccf

**Comment by andrewda** [comment]
Besides the typo on line [46 of your gist](https://gist.github.com/Hello661/ea2da04808a403fdb989797fa5476ccf#file-gistfile1-txt-L46) (it should be `client.gamesPlayed(440)`) your code is working fine for me.

**Comment by Hello661** [comment]
Okay ill try to send another offer
