### ISSUE TITLE
Android link for "How To Find Your Secrets" is down.

### ISSUE THREAD

**Issue by maartenpaauw** [andrewda/node-steam-guide#27]
Just to let you know. The link to the repository (Android guide) is down (404).

**Comment by andrewda** [comment]
Thanks! I'll start to look for an alternative link. If you find one first, let me know!

**Comment by andrewda** [comment]
https://www.reddit.com/r/SteamBot/comments/3w5zwb/info_get_your_2fa_codes_from_android_no_root/

Don't have my Android device to test atm, but that might work.

**Comment by maartenpaauw** [comment]
I don't own an Android device. So I can't confirm if it works. When I was reading the docs I noticed the link wasn't working. 

Maybe someone else with an Android device can confirm if this is working? 👍

**Comment by alicrypto** [comment]
This method does not work for me.

**Comment by alicrypto** [comment]
In the application of Steam there is a restriction on backup and debug. Only use root.

Bad news :(

**Comment by andrewda** [comment]
@alicrypto ah ok. Do you have any links for a tutorial on that?

**Comment by alicrypto** [comment]
@andrewda 
https://github.com/JustArchi/ArchiSteamFarm/wiki/Escrow
https://stackoverflow.com/questions/13006315/how-to-access-data-data-folder-in-android-device
https://stackoverflow.com/questions/1043322/why-do-i-get-access-denied-to-data-folder-when-using-adb
http://denniskubes.com/2012/09/25/read-android-data-folder-without-rooting/

**Comment by andrewda** [comment]
@alicrypto awesome thanks! I'll change the link later today.

**Comment by alicrypto** [comment]
I finally solved this problem. 

I had to disassemble the AIC. Now you can easily retrieve account information using my method.
https://github.com/alicrypto/steam_crack

Testing, pls.

**Comment by andrewda** [comment]
Great, thanks @alicrypto !

**Comment by FinleyCorrigan** [comment]
Can be closed.

**Comment by maartenpaauw** [comment]
The link is still down. Shouldn't it be changed to the one @alicrypto provided?

**Comment by andrewda** [comment]
Slight issue – @alicrypto's account has been deleted and their repository no longer exists. Not sure if anyone forked it. I'm going to link [this one](https://www.reddit.com/r/SteamBot/comments/3w5zwb/info_get_your_2fa_codes_from_android_no_root/) for now. Please open a PR if you'd like to suggest a better one.
