### ISSUE TITLE
Phone number

### ISSUE THREAD

**Issue by alicrypto** [andrewda/node-steam-guide#31]
How can I confirm the phone number on my account? What method?
To use the **enableTwoFactor** method in **steam-user** package.

**Comment by andrewda** [comment]
Good question! I've never actually had to make an account or confirm a phone number from code, but the method you mentioned should work:

https://github.com/DoctorMcKay/node-steam-user#enabletwofactorcallback

That should send you a text message at the phone number provided. Then, input that code into this method:

https://github.com/DoctorMcKay/node-steam-user#finalizetwofactorsecret-activationcode-callback

Should be all set then!
