### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by aero5123** [andrewda/node-steam-guide#32]
i installed the thing four times and it keeps saying the same thing
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\NAME\Documents\node-steam-guide-master\project1.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by andrewda** [comment]
You need to `cd` into the correct directory. I'm guessing you'll need to `cd node-steam-guide/Chapter 1 - Basics/Chapter 1.3 - Starting to Code/`

**Comment by aero5123** [comment]
i am...

**Comment by aero5123** [comment]
i made a separate folder tho
and i installed everything

**Comment by andrewda** [comment]
Type `ls` or `dir` if you're using CMD on Windows. You are definitely _not_ in the right directory.

**Comment by aero5123** [comment]
ok
uh

**Comment by aero5123** [comment]
will do
