### ISSUE TITLE
Add package.json to make installation easier

### ISSUE THREAD

**Issue by andrewda** [andrewda/node-steam-guide#33]
I've been getting a lot of emails wondering how to install dependencies. I'd like to point them to a `package.json` for easy installation.

**Comment by xmwx38** [comment]
Are you thinking of including multiple "package.json" file examples that contain the dependencies for the chapter?

**Comment by andrewda** [comment]
Not sure, honestly. I think it might be best to have a `package.json` inside of every root chapter directory and tell people to install the dependencies using that `package.json` from the prerequisites sub-chapter.

**Comment by xmwx38** [comment]
Could you clarify with examples? I believe I understand you correctly, but just incase! 

I'll begin adding a `package.json` to each root chapter directory.
Example: node-steam-guide/Chapter 6 - Connecting Sites and Bots/

**Comment by andrewda** [comment]
Yep that's what I was thinking. Exactly as you said, in the chapter folders like `Chapter 6 - Connecting Sites and Bots/package.json`.

**Comment by xmwx38** [comment]
I've created a pull request:
#36
