### ISSUE TITLE
The link disabled.

### ISSUE THREAD

**Issue by Soulrun** [andrewda/node-steam-guide#39]
Hello thanks to your tutorial first.
And i found in **Chapter 1.4**-Section **How to find your secrets**

> "...while if you are using an Android you can try` this` tutorial..."

the link of **this**

_https://github.com/SMVampire/SteamBotDev/wiki/Getting-Shared-Secret-from-Android-(Windows)

in detail_
**is an 404 page.**
🙏  hope you can correct it

BTW i am translating you work in order to improve my English level and the skill of node.js
hope you can give a permission of this.
Thank you!

**Comment by andrewda** [comment]
Thanks! This has been reported on #27 – if you have any more suggestions regarding this article, please link them there!
