### ISSUE TITLE
steam-totp issue

### ISSUE THREAD

**Issue by Heldex** [andrewda/node-steam-guide#40]
hey, i just started learning, it's cool!
but I ran into the issue, I read that the steam guard app code thing would be automated but I gotta enter it myself, I used my own code then I tried the example one, still, doesnt work and I took the correct stuff
im sure that i used the correct values, cause i took them from steam desktop authenticator
anyone else ran into this issue and fixed it?

**Comment by andrewda** [comment]
Are you sure you're using your shared secret and not your identity secret? Also is your computer's time accurate?

**Comment by Heldex** [comment]
i managed to fix it, thanks!
yep it was my time.
