### ISSUE TITLE
Possible with web hosting service? (PHP)

### ISSUE THREAD

**Issue by timeisthelimit** [andrewda/node-steam-guide#42]
Leaving aside how much more complicated it would be to do this through a web hosting service. Mainly because this tutorial (which looks like a great tutorial) won't help me with that. My question is simply: Is there a way to make automatic trading using PHP instead of node.js? And also, using a web hosting service vs using my own home server, do I even have enough access to even be able to do the things needed for sending automatic trade requests.

Alternatively, it it possible to handle the automatic bot trading using node.js on my home machine and having it communicate with my website (PHP) hosted by a web hosting service.

Thank you.

**Comment by andrewda** [comment]
Yes - you can do everything here with PHP (though I strongly recommend against it 😛 ). Take a look at https://github.com/waylaidwanderer/PHP-SteamCommunity.

Also, if you're looking for a hosting service, I'd recommend DigitalOcean (or even GAE or AWS if you have experience with them).

**Comment by timeisthelimit** [comment]
Yes, I'd rather stick with node.js but I'm not sure what good host allows node.js. Do the ones you are suggesting allow node.js?

Thanks

**Comment by andrewda** [comment]
Yep! You'll need a VPS host instead of a "Web Host", though. If you just Google "VPS host", tons of options will come up.

**Comment by timeisthelimit** [comment]
Thank you 😁

**Comment by timeisthelimit** [comment]
Also, do you have any VPS host suggestions?
