### ISSUE TITLE
newOffer not firing?

### ISSUE THREAD

**Issue by MordorKing78** [andrewda/node-steam-guide#45]
Why is my newOffer not firing?
```

manager.on('newOffer', (offer) => {
	if (offer.partner.getSteamID64() === '76561198368818576') {
		offer.accept((err, status) => {
			if (err) {
				console.log(err);
			} else {
				console.log(`Accepted offer. Status: ${status}.`);
			}
		});
	} else {
		offer.decline((err) => {
			if (err) {
				console.log(err);
			} else {
				console.log('Canceled offer from scammer.');
			}
		});
	}
});
```

**Comment by andrewda** [comment]
I'm going to need some more details. If you login to the bot's account, can you see the received trade offer? You might also want to add a `console.log` before the if statements.

**Comment by andrewda** [comment]
Also, are you sending the trade offer after the bot is successfully logged on?

**Comment by MordorKing78** [comment]
@andrewda yes, I'm sending the trade after the bot has been logged in which all works fine. I tried to debug in console when the newOffer gets fired, but it doesn't get fired at all.

**Comment by andrewda** [comment]
Have you logged in to the bot's account to make sure the trade offer was actually successfully sent?

**Comment by MordorKing78** [comment]
@andrewda no, but I can see in my history that it was.

**Comment by andrewda** [comment]
And I assume you confirmed the trade offer with the Steam Mobile App?

**Comment by MordorKing78** [comment]
@andrewda yeah, I also tried sending with nothing so I didn't have to confirm it, might there be something wrong with my node modules folder? because it looks like it's extracting everything when I npm a module.

**Comment by MordorKing78** [comment]
![image](https://user-images.githubusercontent.com/6224553/30251759-8f48047a-9666-11e7-9732-6ecd802866cf.png)

**Comment by andrewda** [comment]
If you're not getting any errors, chances are nothing's wrong... I have no idea what the issue could be. The next step for you would be logging into the bot's account to verify that the offer was received.

**Comment by MordorKing78** [comment]
![image](https://user-images.githubusercontent.com/6224553/30251809-945807de-9667-11e7-88be-2da99e2ead31.png)
Coming in just fine

**Comment by MordorKing78** [comment]
I tried with another steam account and it worked.. do you need a steam account that has $5.00 added or something?

**Comment by andrewda** [comment]
Yes, that is a prerequisite.
