### ISSUE TITLE
Incoming trade requests don't trigger event listeners

### ISSUE THREAD

**Issue by NeonWizard** [andrewda/node-steam-guide#47]
I've followed the tutorial up through Chapter 2, but although I've been able to bring my bot account online and change its status, the trade requests don't trigger the event listener.

**Comment by andrewda** [comment]
I should make this more clear in the guide. You need a premium account (i.e. an account with at least a $5 purchase on Steam) in order to perform trades and have access to the API. See #45.

**Comment by NeonWizard** [comment]
Sorry, I should've clarified as well. I went through all of the steps to verify the bot - made a $5 purchase, waited over two weeks, etc etc. I am able to make a trade while logged into the bot and I'm also able to make a trade with the bot itself, but the event listener just doesn't trigger.

**Comment by andrewda** [comment]
Interesting, alright. A couple more questions to sift out some of the easy solutions:

Is the bot logged in _before_ you send the trade offer? Does the logged in message appear in the console?

**Comment by NeonWizard** [comment]
Yes, the bot authenticates and the 'loggedOn' event listener is called properly. There are no errors on the confirmationChecker or anywhere else. I put a console.log in the 'newOffer' callback but it's never reached when a trade is made.

**Comment by NeonWizard** [comment]
Right, I figured out the problem. I was using an old identity secret from a different account, which for some reason wasn't throwing an error when used in the confirmationChecker. My bad.

**Comment by andrewda** [comment]
Yea, it silently fails. Glad you got it working!
