### ISSUE TITLE
Check arguments

### ISSUE THREAD

**Issue by vortexcodes** [andrewda/node-steam-guide#48]
!test hello

if argument is hello send message. How can do it?

**Comment by andrewda** [comment]
Here's an easy way to do what you're looking for:

```
user.on('friendMessage', function(steamid, message) {
    const parts = message.split(' ');

    console.log(`Command: ${parts[0]}`);
    console.log(`Argument 1: ${parts[1]}`);
});
```

**Comment by vortexcodes** [comment]
nothing happen in console?

**Comment by andrewda** [comment]
Make sure you send the bot a message while it's online. If you do (and don't get any errors anywhere), that could should work fine.

**Comment by vortexcodes** [comment]
When only !test 
Command: !test 
Argument 1: undefined

But !test hello
nothing happen

**Comment by vortexcodes** [comment]
**How can fix it?**

**Comment by vortexcodes** [comment]
if(${parts[1]} == "123") {
        ^

SyntaxError: Unexpected token {
how can fix it?

**Comment by vortexcodes** [comment]
Fixed, nevermind. Thanks ^^

**Comment by xmwx38** [comment]
@vortexcodes If you could, please post how you fixed it.
