### ISSUE TITLE
Page timing out

### ISSUE THREAD

**Issue by mikirov** [andrewda/node-steam-guide#49]
I tried project 10 on vps server and the page did not load in time. I checked the console and it said that the app was listening (i made the connection on port 5000 instead of 3037) , the bot was working , i had all the modules necessary. I cant see why the page is timing out. Do i need to write the domain name instead of localhost:5000 or am i missing something?
Edit: I checked and saw that it was the socket taking too long to connect with the user. Its probably because im using NGINX to reverse proxy requests (to setup https sertificate). Any suggestions how to fix it ?

**Comment by andrewda** [comment]
If you're running it on a VPS, then yes, you'll need to use the server IP rather than `localhost` when navigating to it in your browser. `localhost` only accesses your local computer.
