### ISSUE TITLE
Problem saving information in database 

### ISSUE THREAD

**Issue by shimonchick** [andrewda/node-steam-guide#55]
Hello. 
I tried running project 6 and it seems to be working fine , exept one thing : It doesn't save any information to the database. I checked using mongo and it had database "guide" that had 3 collections: "prices" , "sessions" and "users" , none of them had any info. It also desn't show anything in the withdraw page on the app.
 How do i get them to run properly ?

**Comment by xmwx38** [comment]
How did you fix this, if you did?  I would love to know.
