### ISSUE TITLE
When are updates to this tutorial coming?

### ISSUE THREAD

**Issue by f-corrigan** [andrewda/node-steam-guide#58]
It's been a long time...

**Comment by bdalli93** [comment]
I hope he will continue as well, but since he is not getting payment for this, I believe you should be more polite 👍

**Comment by xmwx38** [comment]
[**Issue #63** ](https://github.com/andrewda/node-steam-guide/issues/63) should be merged here.  As it deals with the same subject of future updates

**Comment by xmwx38** [comment]
I have forked node-steam-guide & have made about 15 updates.  Check it out here...
https://github.com/Steam-bot-basics/node-steam-guide

**Comment by andrewda** [comment]
See #100 :D
