### ISSUE TITLE
Cannot overwrite `User` model once compiled.

### ISSUE THREAD

**Issue by mohamadgh** [andrewda/node-steam-guide#59]
Hey everyone!
i have put all the code step by step in my files and named them exactly the same as the guide 
i have mongodb and nodejs installed and running and i'm still getting this error when i try to run app.js
![capture](https://user-images.githubusercontent.com/34480447/33892314-59a9492e-df0d-11e7-8444-89280f2669ac.PNG)

can anyone help me with this please
thanks in advance

**Comment by andrewda** [comment]
You seem to be trying to compile the same Mongoose model twice, or at least two models that have the same name. Look at your models and make sure they are all named differently (probably a copy-paste error and you forgot to change `User` to `Item` :wink:)

**Comment by mohamadgh** [comment]
Thanks for responding o/

**Comment by mohamadgh** [comment]
![error](https://user-images.githubusercontent.com/34480447/33910511-d6f9267a-df43-11e7-813d-c56f4df76eab.PNG)
can you help me with this one please
i have the config.json,
with a valid api key and a secret string.
config.json and app.js are in the same folder .
