### ISSUE TITLE
chapter 2-2: bot doesn't react to new tradeoffers

### ISSUE THREAD

**Issue by reJecTcs** [andrewda/node-steam-guide#6]
I followed your guide (thank you a lot btw) and everything went smooth so far, now I'm stuck though as the bot won't react to sent tradeoffers. From what I understand the even newOffer is never registered (I could be wrong I'm pretty new to coding). The bot definitely does get the offers, I can even log into the account and accept them manually. I downloaded your code and tried with that still no luck. Any help would be appreciated!

**Comment by andrewda** [comment]
The event which is triggered when you receive an event is located [here](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%202%20-%20Trading/Chapter%202.2%20-%20Handling%20Trade%20Offers/project2.js#L36-L54). Also - make sure your bot is actually successfully logging in and that the bot is on when it receives an offer.

**Comment by reJecTcs** [comment]
Bot is logged in, I get the message from the cmd and I can see him online. I tried a console log in front of the if statement under the manager.on but got no results either. The webSession listen seems to work as I can print the sessionid and cookies. What's the best way to make sure the manager instance is running?

**Comment by andrewda** [comment]
Hmm, interesting. I would recommend adding the following code to your app and tell me what it outputs:

```js
manager.on('pollFailure', () => {
    console.log('poll failure');
});

manager.on('debug', (msg) => {
    console.log(`debug: ${msg}`);
});
```

**Comment by DopplaCSGO** [comment]
@andrewda This isn't part of the issue, but I can't find a way to thank you for making this great tutorial and to tell you to keep going with it! I'm looking forwards to being able to fetch and show a users inventory on the site!

**Comment by andrewda** [comment]
@DopplaCSGO sure no problem! Hope it helps and proves useful!

**Comment by DopplaCSGO** [comment]
@andrewda Thanks! Just be sure to bless us with it soon and not let it die! <3

**Comment by reJecTcs** [comment]
thank you for your efforts; it was an issue with the account. I tried on a different one and it worked just fine. Sorry for stealing your time.

**Comment by PredatorIWD** [comment]
@andrewda So this will only work on steam account that are not limited? You have to spend 5$ first to be able to accept donations? Thanks for guide tho man.
