### ISSUE TITLE
ReferenceError: config is not defined

### ISSUE THREAD

**Issue by mohamadgh** [andrewda/node-steam-guide#60]
i'm facing another issue here...
hopefully this will be the last
![error](https://user-images.githubusercontent.com/34480447/33951967-4244ea08-dfe5-11e7-8db6-eb74cf4828c3.PNG)
config.json and app.js are in the same folder
inside config.json i've entered a valid secret string and api key but still getting this error message
sorry for my poor English.

**Comment by andrewda** [comment]
Looks like you're not requiring the config file. Add this to the top of your `app.js`:

```javascript
const config = require('./config.json');
```

**Comment by mohamadgh** [comment]
i'm using the same source, i don't know why i keep getting errors :D

**Comment by Samcool236** [comment]
I'm having the same issue. 

For some reason, it seems to recognise helper.js, no matter with or without the file suffix. 
However, it cannot recognise any .json file in my whole project.

![json vs js](https://user-images.githubusercontent.com/38600650/51814009-55a5ff80-230d-11e9-90e6-2c6f30ccafe8.png)

**Comment by andrewda** [comment]
@Samcool236 where are your JSON files located? Your require statements indicated that your JSON files are in the directory above your code. Could you post a screenshot of your code structure?

**Comment by YorkWong30** [comment]
i have same error.

**Comment by JMDServidio** [comment]
in index.blade.php , search windows.config....   and  delete this line -> "debug": {{ env('APP_DEBUG') }}       :D
