### ISSUE TITLE
Module not found ! Please help

### ISSUE THREAD

**Issue by matusik484** [andrewda/node-steam-guide#65]
![bez nazvu](https://user-images.githubusercontent.com/35899947/35485815-115b617a-0465-11e8-90cb-3e1b44f3549b.png)

**Comment by iDefineHD** [comment]
why are you trying to run a .json ? it should be (node bot.js) or (node bot)

**Comment by matusik484** [comment]
iDefineHD when i run filé že bot.js its same error !

**Comment by iDefineHD** [comment]
Have you installed the actual modules required for this project then?

**Comment by matusik484** [comment]
Yes I installed required modules but when i add steam totp to code start and after 1 second shut down node

**Comment by iDefineHD** [comment]
If you want. I shall take a look for you later.
