### ISSUE TITLE
Next problem with steam-totp !

### ISSUE THREAD

**Issue by matusik484** [andrewda/node-steam-guide#66]
When I add  twoFactorCode: SteamTotp.generateAuthCode('my shared secret key') he was crashing the console ! He was working when i add this steam-totp :(

Andrewda please help

**Comment by DentFuse** [comment]
It's really confusing to understand what you mean, if you mean to say that the app is crashing when you remove : ```const SteamTotp = require('steam-totp');``` then that's what supposed to happen because ```steam-totp``` is required to generate Steam Guard using ```SteamTotp.generateAuthCode('shared_secret')```

If this is not what you mean, please be more clear with your question.
