### ISSUE TITLE
Withdraw page

### ISSUE THREAD

**Issue by AidaMati** [andrewda/node-steam-guide#70]
Hi, I just finished the 6th chapter but my withdraw page looks like this: http://prntscr.com/iarsdb. Even though I have no traces of any redlines or asiimovs in my codes. How can I fix this? How can I have it load skins from my bot's inventory?

**Comment by AidaMati** [comment]
@andrewda

**Comment by xmwx38** [comment]
@AidaMati; How did you resolve this issue?  I'm curious.

**Comment by AidaMati** [comment]
I think it kinda fixed itself. I had it load items from user's inventory, since then the asiimovs and redlines haven't shown up.
Might've been a Mongo issue but not sure.
