### ISSUE TITLE
Code Protection ? (Not exactly an issue, but a question)

### ISSUE THREAD

**Issue by DentFuse** [andrewda/node-steam-guide#76]
Hi all, 
First I would like to thank the writers of this guide, it's awesome! So my question, if I ever had to sell the bot I write, how do I do it? Do I just give the source code? Cause that would leak my code, so is there a specific way I should do the trade, maybe like compile the code and then send it? Any help would be appreciated :)

**Comment by DentFuse** [comment]
@FinleyCorrigan So then compiling code (using pkg) isn't an option?

**Comment by FinleyCorrigan** [comment]
Yes it is possible to obfuscate code... there are many online tools that will do it (you enter the code, they encrypt it and provide you with an encryption key), but why would you need to encrypt code?

**Comment by DentFuse** [comment]
@FinleyCorrigan Thank you for ur suggestion of selling my code only once. That actually makes more sense than compiling the code. Also I wasn't talking about encrypting the code, but instead compiling it, so it is still runs, it's just that the code isn't released.
