### ISSUE TITLE
SteamBot is not a constructor

### ISSUE THREAD

**Issue by vidit-agarwal** [andrewda/node-steam-guide#83]
# In chapter 6 , part 3 . 
Where ur doing connection. The code in app.js is giving an error on instantiating the SteamBot class. I have written code : 
**const bot = new SteamBot({...}) ;**

> on running both index.js and app.js. It is showing error in app.js that SteamBot is not a constructor 

![image](https://user-images.githubusercontent.com/23436981/38287049-232fd6ba-37e6-11e8-8f5b-cee000c94071.png)

**Comment by andrewda** [comment]
I'm guessing you're not importing the required SteamBot class. Look at https://github.com/andrewda/node-steam-guide/tree/master/Chapter%206%20-%20Connecting%20Sites%20and%20Bots/Chapter%206.3%20-%20Beginning%20the%20Connection/project10 for complete code.

**Comment by vidit-agarwal** [comment]
Thanks for reply . But i have figured it out earlier this morning . It was not due to the import error , it was of something else . So , its now resolved . Thanks for this guide . I am implementing this in php and nodejs mixture . Your code is quite helpful for me for making bot
