### ISSUE TITLE
Can't login to site

### ISSUE THREAD

**Issue by AidaMati** [andrewda/node-steam-guide#86]
I haven't run the bot or site in a few months until now. When I click "Login", it takes me to steam login, I log in and it redirects me to my home page, bit it's still not logged in. What might be the issue?

**Comment by AidaMati** [comment]
Note that it did work perfectly the last time I used it..

**Comment by andrewda** [comment]
What version of `passport-steam` are you using? Ensure it's at least `v1.0.9`.

**Comment by AidaMati** [comment]
Updated, working now. Thanks!
