### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by irmandos** [andrewda/node-steam-guide#9]
Good Day, 
I have been following your work (I love it) but I have run into a few issues with the latest code. ([Chapter 6.1 - Getting Started](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%206%20-%20Connecting%20Sites%20and%20Bots/Chapter%206.1%20-%20Getting%20Started))

Here is the steps I followed:
- Verified dependancies are installed as listed. ([Chapter 2.1](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%202%20-%20Trading/Chapter%202.1%20-%20Prerequisites),[Chapter 4.1](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%204%20-%20Basics%20of%20Web%20Development/Chapter%204.1%20-%20Prerequisites),[Chapter 5.1](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%205%20-%20Advanced%20Web%20Development/Chapter%205.1%20-%20Prerequisites))
- Removed my folder structure, re-created the folder structure, re-installed dependancies, and downloaded the files directly from GitHub using wget.

Technical Details about my environment:
- Ubuntu 16 xenial, hosted on the Google Cloud platform
- Firewall enabled with exception to port 3037

1. 1st Error
>irmandos@alfred-container:~/trade-bot$ node app.js 
>module.js:442
>    throw err;
>    ^
>
>Error: Cannot find module 'passport.socketio'
>    at Function.Module._resolveFilename (module.js:440:15)
>    at Function.Module._load (module.js:388:25)
>    at Module.require (module.js:468:17)
>    at require (internal/module.js:20:19)
>    at Object.<anonymous> (/home/irmandos/trade-bot/app.js:5:24)
>    at Module._compile (module.js:541:32)
>    at Object.Module._extensions..js (module.js:550:10)
>    at Module.load (module.js:458:32)
>    at tryModuleLoad (module.js:417:12)

When I remove the `const passportSocket = require('passport.socketio');` section in app.js it continues to the 2nd error

2. 2nd Error
>irmandos@alfred-container:~/trade-bot$ node app.js 
>module.js:442
>    throw err;
>    ^
>
>Error: Cannot find module 'connect-mongo'
>    at Function.Module._resolveFilename (module.js:440:15)
>    at Function.Module._load (module.js:388:25)
>    at Module.require (module.js:468:17)
>    at require (internal/module.js:20:19)
>    at Object.<anonymous> (/home/irmandos/trade-bot/app.js:13:20)
>    at Module._compile (module.js:541:32)
>    at Object.Module._extensions..js (module.js:550:10)
>    at Module.load (module.js:458:32)
>    at tryModuleLoad (module.js:417:12)
>    at Function.Module._load (module.js:409:3)
>    at Module.runMain (module.js:575:10)
>    at run (node.js:348:7)
>    at startup (node.js:140:9)
>    at node.js:463:3

When I remove the `const MongoStore = require('connect-mongo')(session);` section in app.js it continues to the 3rd error.

3. 3rd Error
>irmandos@alfred-container:~/trade-bot$ node app.js 
>/home/irmandos/trade-bot/app.js:28
>const sessionStore = new MongoStore({ mongooseConnection: mongoose.connection });
>                         ^
>
>ReferenceError: MongoStore is not defined
>    at Object.<anonymous> (/home/irmandos/trade-bot/app.js:28:26)
>    at Module._compile (module.js:541:32)
>    at Object.Module._extensions..js (module.js:550:10)
>    at Module.load (module.js:458:32)
>    at tryModuleLoad (module.js:417:12)
>    at Function.Module._load (module.js:409:3)
>    at Module.runMain (module.js:575:10)
>    at run (node.js:348:7)
>    at startup (node.js:140:9)
>    at node.js:463:3

**Comment by iDefineHD** [comment]
These npm packagea dont exist. Hence the errors.

**Comment by irmandos** [comment]
I can understand that, thank you, it makes sense.

But where then do I find these packages? (I'm looking through the posts but I also don't see any references as to where they are located)

**Comment by iDefineHD** [comment]
Well passport and socket.io are seperate packages. Installed as npm install passport and npm install socket.io , mongo will also follow the same install like the others.

**Comment by irmandos** [comment]
@iDefineHD , thank you again for your comment but I don't believe it is correct.
As per my original post I confirmed that I have installed all the dependencies as per the various sections.

Here is my current installation through NPM:
>irmandos@alfred-container:~/trade-bot$ npm list --depth=0
/home/irmandos/trade-bot
├── cookie-parser@1.4.3
├── express@4.14.0
├── express-handlebars@3.0.0
├── express-session@1.14.2
├── mongoose@4.7.7
├── morgan@1.7.0
├── passport@0.3.2
├── passport-steam@1.0.7
├── socket.io@1.7.2
├── steam-totp@1.4.0
├── steam-tradeoffer-manager@2.5.0
├── steam-user@3.15.0
└── steamcommunity@3.30.3

**Comment by iDefineHD** [comment]
Oh ok. Was just a base thought as it was trying to get packages that were not found. I will have a bettee look kater when i get home. I will then have more time to look over and sort out with you.

**Comment by andrewda** [comment]
You need to install both modules. If you ever get an error like "Cannot find module X" it's safe to assume you just haven't installed the module. In your case, follow the commands below:

`npm i passport.socketio` (NPM: https://www.npmjs.com/package/passport.socketio)
`npm i connect-mongo` (NPM: https://www.npmjs.com/package/connect-mongo)
