### ISSUE TITLE
EPersona Problem

### ISSUE THREAD

**Issue by DatColdCat** [andrewda/node-steam-guide#94]
Every time that I run this code - 
"const SteamUser = require('steam-user');
const config = require('./config.json');
const client = new SteamUser();

const logOnOptions = {
  accountName: config.username,
  password: config.password
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
  console.log('Logged into Steam');

  client.setPersona(SteamUser.Steam.EPersonaState.Online);
  client.gamesPlayed(440);
});"

I get this error -
 "client.setPersona(SteamUser.Steam.ePersonaState.Online);
                                                    ^

TypeError: Cannot read property 'ePersonaState' of undefined"

Is there a problem with that I have down?

**Comment by Billason** [comment]
client.setPersona(SteamUser.EPersonaState.Online);
Hope for it

**Comment by PlasmaSnake** [comment]
> **client.setPersona(SteamUser.EPersonaState.Online);**
> Hope for it****

Seems to have worked for me!

**Comment by spyM4trix** [comment]
i have the same problem

**Comment by sp0ok3r** [comment]
1 = online

**Comment by spyM4trix** [comment]
> 1 = online

that doesnt help it still says TypeEror : ... EPersonaState

**Comment by Billason** [comment]
client.setPersona(SteamUser.EPersonaState.Online);
I think lol

**Comment by sp0ok3r** [comment]
use this repo: https://github.com/DoctorMcKay/node-steam-user

**Comment by agasking1337** [comment]
This is correct 
Client.setEPersona(SteamUser.Steam.EPersonaState.Online);

**Comment by redBaron23** [comment]
Same error, but if i try using the folder of this project installing dependencies, it's working

**Comment by ElijahWoelbing** [comment]
same error :/

**Comment by pringles4** [comment]
sup, have the same problem: (new to this stuff)
(I have also tried SteamUser.Steam.EPersonaState.Online

const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const config = require('./config.json');
const client = new SteamUser();

const logOnOptions = {
  accountName: config.username,
  password: config.password,
  twoFactorCode: SteamTotp.generateAuthCode(config.sharedSecret)
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
  console.log('Success login');
  client.setPersona(SteamUser.EPersonaState.Online);
});


C:\Users\acer\Desktop\bot\index.js:18
        client.setPersona(SteamUser.Steam.EPersonaState.Online);
                                          ^

TypeError: Cannot read property 'EPersonaState' of undefined

**Comment by sapphiremonkey** [comment]
@pringles4 

Try removing the `.Steam` snippet of code from this

> C:\Users\acer\Desktop\bot\index.js:18
> client.setPersona(SteamUser**.Steam**.EPersonaState.Online);

to this 

> client.setPersona(SteamUserEPersonaState.Online);

**Comment by pringles4** [comment]
I wanted to test this out, so i got in changed it.
If i type node index.js in nothing happens no "logged on" no  Errors I really don't knwo what to do

**Comment by unknown0520** [comment]
I got same problem, and finally I solved it by simply write it like this:

> client.setPersona(1);
